[rke2_servers]

rke2-test-server-01 ansible_host=44.193.72.113 public_ip=44.193.72.113 private_ip=10.0.1.82 anisble_user=ec2-user

rke2-test-server-02 ansible_host=3.83.10.118 public_ip=3.83.10.118 private_ip=10.0.2.137 anisble_user=ec2-user

rke2-test-server-03 ansible_host=54.208.225.224 public_ip=54.208.225.224 private_ip=10.0.3.5 anisble_user=ec2-user

[rke2_agents]

rke2-test-agent-01 ansible_host=44.220.90.38 public_ip=44.220.90.38 private_ip=10.0.1.161 ansible_user=ec2-user

rke2-test-agent-02 ansible_host=3.86.86.167 public_ip=3.86.86.167 private_ip=10.0.2.68 ansible_user=ec2-user

rke2-test-agent-03 ansible_host=98.88.73.211 public_ip=98.88.73.211 private_ip=10.0.3.55 ansible_user=ec2-user

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/.ssh/id_rsa.pub
